### ISSUE TITLE
Options of HOMER in the reference paper

### ISSUE THREAD

**Issue by soobeomlee** [danobaji/AppGen_Finalproject#1]
Hey Daniel, I think that it would be better to use same options that the original paper used. 

From the supplementary information: 

"The identification of ChIP-seq enriched regions (peaks) in each sample was performed using
HOMER (http://homer.salk.edu/homer/). For histone modifications, peaks were identified by
searching locations of high read density using a 1000 bp sliding window. We required adjacent
peaks to be at least 1000 bp away to avoid redundant detection. The threshold for the number of
tags that determined a valid peak was selected at a false discovery rate of 0.001. The following
HOMER command was used:
cmd = findPeaks <sample tag directory> -L 0 -C 3 -size 1000 -
minDist 1000 -tbp 3 -o <output file> "

**Comment by danobaji** [comment]
Updated!
